/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package models.avro;

import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.SchemaStore;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;

@org.apache.avro.specific.AvroGenerated
public class GcsPartitioner extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -4067784289860502966L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"GcsPartitioner\",\"namespace\":\"models.avro\",\"fields\":[{\"name\":\"pattern\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"value\",\"type\":[\"null\",\"string\"],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<GcsPartitioner> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<GcsPartitioner> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<GcsPartitioner> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<GcsPartitioner> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<GcsPartitioner> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this GcsPartitioner to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a GcsPartitioner from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a GcsPartitioner instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static GcsPartitioner fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private CharSequence pattern;
  private CharSequence value;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public GcsPartitioner() {}

  /**
   * All-args constructor.
   * @param pattern The new value for pattern
   * @param value The new value for value
   */
  public GcsPartitioner(CharSequence pattern, CharSequence value) {
    this.pattern = pattern;
    this.value = value;
  }

  @Override
  public SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public Object get(int field$) {
    switch (field$) {
    case 0: return pattern;
    case 1: return value;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, Object value$) {
    switch (field$) {
    case 0: pattern = (CharSequence)value$; break;
    case 1: value = (CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'pattern' field.
   * @return The value of the 'pattern' field.
   */
  public CharSequence getPattern() {
    return pattern;
  }


  /**
   * Sets the value of the 'pattern' field.
   * @param value the value to set.
   */
  public void setPattern(CharSequence value) {
    this.pattern = value;
  }

  /**
   * Gets the value of the 'value' field.
   * @return The value of the 'value' field.
   */
  public CharSequence getValue() {
    return value;
  }


  /**
   * Sets the value of the 'value' field.
   * @param value the value to set.
   */
  public void setValue(CharSequence value) {
    this.value = value;
  }

  /**
   * Creates a new GcsPartitioner RecordBuilder.
   * @return A new GcsPartitioner RecordBuilder
   */
  public static models.avro.GcsPartitioner.Builder newBuilder() {
    return new models.avro.GcsPartitioner.Builder();
  }

  /**
   * Creates a new GcsPartitioner RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new GcsPartitioner RecordBuilder
   */
  public static models.avro.GcsPartitioner.Builder newBuilder(models.avro.GcsPartitioner.Builder other) {
    if (other == null) {
      return new models.avro.GcsPartitioner.Builder();
    } else {
      return new models.avro.GcsPartitioner.Builder(other);
    }
  }

  /**
   * Creates a new GcsPartitioner RecordBuilder by copying an existing GcsPartitioner instance.
   * @param other The existing instance to copy.
   * @return A new GcsPartitioner RecordBuilder
   */
  public static models.avro.GcsPartitioner.Builder newBuilder(models.avro.GcsPartitioner other) {
    if (other == null) {
      return new models.avro.GcsPartitioner.Builder();
    } else {
      return new models.avro.GcsPartitioner.Builder(other);
    }
  }

  /**
   * RecordBuilder for GcsPartitioner instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<GcsPartitioner>
    implements org.apache.avro.data.RecordBuilder<GcsPartitioner> {

    private CharSequence pattern;
    private CharSequence value;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(models.avro.GcsPartitioner.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.pattern)) {
        this.pattern = data().deepCopy(fields()[0].schema(), other.pattern);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.value)) {
        this.value = data().deepCopy(fields()[1].schema(), other.value);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing GcsPartitioner instance
     * @param other The existing instance to copy.
     */
    private Builder(models.avro.GcsPartitioner other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.pattern)) {
        this.pattern = data().deepCopy(fields()[0].schema(), other.pattern);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.value)) {
        this.value = data().deepCopy(fields()[1].schema(), other.value);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'pattern' field.
      * @return The value.
      */
    public CharSequence getPattern() {
      return pattern;
    }


    /**
      * Sets the value of the 'pattern' field.
      * @param value The value of 'pattern'.
      * @return This builder.
      */
    public models.avro.GcsPartitioner.Builder setPattern(CharSequence value) {
      validate(fields()[0], value);
      this.pattern = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'pattern' field has been set.
      * @return True if the 'pattern' field has been set, false otherwise.
      */
    public boolean hasPattern() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'pattern' field.
      * @return This builder.
      */
    public models.avro.GcsPartitioner.Builder clearPattern() {
      pattern = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'value' field.
      * @return The value.
      */
    public CharSequence getValue() {
      return value;
    }


    /**
      * Sets the value of the 'value' field.
      * @param value The value of 'value'.
      * @return This builder.
      */
    public models.avro.GcsPartitioner.Builder setValue(CharSequence value) {
      validate(fields()[1], value);
      this.value = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'value' field has been set.
      * @return True if the 'value' field has been set, false otherwise.
      */
    public boolean hasValue() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'value' field.
      * @return This builder.
      */
    public models.avro.GcsPartitioner.Builder clearValue() {
      value = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public GcsPartitioner build() {
      try {
        GcsPartitioner record = new GcsPartitioner();
        record.pattern = fieldSetFlags()[0] ? this.pattern : (CharSequence) defaultValue(fields()[0]);
        record.value = fieldSetFlags()[1] ? this.value : (CharSequence) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<GcsPartitioner>
    WRITER$ = (org.apache.avro.io.DatumWriter<GcsPartitioner>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<GcsPartitioner>
    READER$ = (org.apache.avro.io.DatumReader<GcsPartitioner>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    if (this.pattern == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.pattern);
    }

    if (this.value == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.value);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      if (in.readIndex() != 1) {
        in.readNull();
        this.pattern = null;
      } else {
        this.pattern = in.readString(this.pattern instanceof Utf8 ? (Utf8)this.pattern : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.value = null;
      } else {
        this.value = in.readString(this.value instanceof Utf8 ? (Utf8)this.value : null);
      }

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          if (in.readIndex() != 1) {
            in.readNull();
            this.pattern = null;
          } else {
            this.pattern = in.readString(this.pattern instanceof Utf8 ? (Utf8)this.pattern : null);
          }
          break;

        case 1:
          if (in.readIndex() != 1) {
            in.readNull();
            this.value = null;
          } else {
            this.value = in.readString(this.value instanceof Utf8 ? (Utf8)this.value : null);
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










