/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package models.avro.wager.avro.wager;

import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.SchemaStore;
import org.apache.avro.specific.SpecificData;

@org.apache.avro.specific.AvroGenerated
public class Wager_odds extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -8523929042345983743L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Wager_odds\",\"namespace\":\"models.avro.wager\",\"fields\":[{\"name\":\"player\",\"type\":[\"null\",{\"type\":\"record\",\"name\":\"Wager_odds_player\",\"fields\":[{\"name\":\"format\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"value\",\"type\":[\"null\",\"double\"],\"default\":null}]}],\"default\":null},{\"name\":\"system\",\"type\":[\"null\",{\"type\":\"record\",\"name\":\"Wager_odds_system\",\"fields\":[{\"name\":\"format\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"value\",\"type\":[\"null\",\"double\"],\"default\":null}]}],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Wager_odds> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Wager_odds> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Wager_odds> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Wager_odds> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Wager_odds> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Wager_odds to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Wager_odds from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Wager_odds instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Wager_odds fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private Wager_odds_player player;
  private Wager_odds_system system;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Wager_odds() {}

  /**
   * All-args constructor.
   * @param player The new value for player
   * @param system The new value for system
   */
  public Wager_odds(Wager_odds_player player, Wager_odds_system system) {
    this.player = player;
    this.system = system;
  }

  @Override
  public SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public Object get(int field$) {
    switch (field$) {
    case 0: return player;
    case 1: return system;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, Object value$) {
    switch (field$) {
    case 0: player = (Wager_odds_player)value$; break;
    case 1: system = (Wager_odds_system)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'player' field.
   * @return The value of the 'player' field.
   */
  public Wager_odds_player getPlayer() {
    return player;
  }


  /**
   * Sets the value of the 'player' field.
   * @param value the value to set.
   */
  public void setPlayer(Wager_odds_player value) {
    this.player = value;
  }

  /**
   * Gets the value of the 'system' field.
   * @return The value of the 'system' field.
   */
  public Wager_odds_system getSystem() {
    return system;
  }


  /**
   * Sets the value of the 'system' field.
   * @param value the value to set.
   */
  public void setSystem(Wager_odds_system value) {
    this.system = value;
  }

  /**
   * Creates a new Wager_odds RecordBuilder.
   * @return A new Wager_odds RecordBuilder
   */
  public static Wager_odds.Builder newBuilder() {
    return new Wager_odds.Builder();
  }

  /**
   * Creates a new Wager_odds RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Wager_odds RecordBuilder
   */
  public static Wager_odds.Builder newBuilder(Wager_odds.Builder other) {
    if (other == null) {
      return new Wager_odds.Builder();
    } else {
      return new Wager_odds.Builder(other);
    }
  }

  /**
   * Creates a new Wager_odds RecordBuilder by copying an existing Wager_odds instance.
   * @param other The existing instance to copy.
   * @return A new Wager_odds RecordBuilder
   */
  public static Wager_odds.Builder newBuilder(Wager_odds other) {
    if (other == null) {
      return new Wager_odds.Builder();
    } else {
      return new Wager_odds.Builder(other);
    }
  }

  /**
   * RecordBuilder for Wager_odds instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Wager_odds>
    implements org.apache.avro.data.RecordBuilder<Wager_odds> {

    private Wager_odds_player player;
    private Wager_odds_player.Builder playerBuilder;
    private Wager_odds_system system;
    private Wager_odds_system.Builder systemBuilder;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(Wager_odds.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.player)) {
        this.player = data().deepCopy(fields()[0].schema(), other.player);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (other.hasPlayerBuilder()) {
        this.playerBuilder = Wager_odds_player.newBuilder(other.getPlayerBuilder());
      }
      if (isValidValue(fields()[1], other.system)) {
        this.system = data().deepCopy(fields()[1].schema(), other.system);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (other.hasSystemBuilder()) {
        this.systemBuilder = Wager_odds_system.newBuilder(other.getSystemBuilder());
      }
    }

    /**
     * Creates a Builder by copying an existing Wager_odds instance
     * @param other The existing instance to copy.
     */
    private Builder(Wager_odds other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.player)) {
        this.player = data().deepCopy(fields()[0].schema(), other.player);
        fieldSetFlags()[0] = true;
      }
      this.playerBuilder = null;
      if (isValidValue(fields()[1], other.system)) {
        this.system = data().deepCopy(fields()[1].schema(), other.system);
        fieldSetFlags()[1] = true;
      }
      this.systemBuilder = null;
    }

    /**
      * Gets the value of the 'player' field.
      * @return The value.
      */
    public Wager_odds_player getPlayer() {
      return player;
    }


    /**
      * Sets the value of the 'player' field.
      * @param value The value of 'player'.
      * @return This builder.
      */
    public Wager_odds.Builder setPlayer(Wager_odds_player value) {
      validate(fields()[0], value);
      this.playerBuilder = null;
      this.player = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'player' field has been set.
      * @return True if the 'player' field has been set, false otherwise.
      */
    public boolean hasPlayer() {
      return fieldSetFlags()[0];
    }

    /**
     * Gets the Builder instance for the 'player' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public Wager_odds_player.Builder getPlayerBuilder() {
      if (playerBuilder == null) {
        if (hasPlayer()) {
          setPlayerBuilder(Wager_odds_player.newBuilder(player));
        } else {
          setPlayerBuilder(Wager_odds_player.newBuilder());
        }
      }
      return playerBuilder;
    }

    /**
     * Sets the Builder instance for the 'player' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */

    public Wager_odds.Builder setPlayerBuilder(Wager_odds_player.Builder value) {
      clearPlayer();
      playerBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'player' field has an active Builder instance
     * @return True if the 'player' field has an active Builder instance
     */
    public boolean hasPlayerBuilder() {
      return playerBuilder != null;
    }

    /**
      * Clears the value of the 'player' field.
      * @return This builder.
      */
    public Wager_odds.Builder clearPlayer() {
      player = null;
      playerBuilder = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'system' field.
      * @return The value.
      */
    public Wager_odds_system getSystem() {
      return system;
    }


    /**
      * Sets the value of the 'system' field.
      * @param value The value of 'system'.
      * @return This builder.
      */
    public Wager_odds.Builder setSystem(Wager_odds_system value) {
      validate(fields()[1], value);
      this.systemBuilder = null;
      this.system = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'system' field has been set.
      * @return True if the 'system' field has been set, false otherwise.
      */
    public boolean hasSystem() {
      return fieldSetFlags()[1];
    }

    /**
     * Gets the Builder instance for the 'system' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public Wager_odds_system.Builder getSystemBuilder() {
      if (systemBuilder == null) {
        if (hasSystem()) {
          setSystemBuilder(Wager_odds_system.newBuilder(system));
        } else {
          setSystemBuilder(Wager_odds_system.newBuilder());
        }
      }
      return systemBuilder;
    }

    /**
     * Sets the Builder instance for the 'system' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */

    public Wager_odds.Builder setSystemBuilder(Wager_odds_system.Builder value) {
      clearSystem();
      systemBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'system' field has an active Builder instance
     * @return True if the 'system' field has an active Builder instance
     */
    public boolean hasSystemBuilder() {
      return systemBuilder != null;
    }

    /**
      * Clears the value of the 'system' field.
      * @return This builder.
      */
    public Wager_odds.Builder clearSystem() {
      system = null;
      systemBuilder = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Wager_odds build() {
      try {
        Wager_odds record = new Wager_odds();
        if (playerBuilder != null) {
          try {
            record.player = this.playerBuilder.build();
          } catch (org.apache.avro.AvroMissingFieldException e) {
            e.addParentField(record.getSchema().getField("player"));
            throw e;
          }
        } else {
          record.player = fieldSetFlags()[0] ? this.player : (Wager_odds_player) defaultValue(fields()[0]);
        }
        if (systemBuilder != null) {
          try {
            record.system = this.systemBuilder.build();
          } catch (org.apache.avro.AvroMissingFieldException e) {
            e.addParentField(record.getSchema().getField("system"));
            throw e;
          }
        } else {
          record.system = fieldSetFlags()[1] ? this.system : (Wager_odds_system) defaultValue(fields()[1]);
        }
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Wager_odds>
    WRITER$ = (org.apache.avro.io.DatumWriter<Wager_odds>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Wager_odds>
    READER$ = (org.apache.avro.io.DatumReader<Wager_odds>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    if (this.player == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      this.player.customEncode(out);
    }

    if (this.system == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      this.system.customEncode(out);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      if (in.readIndex() != 1) {
        in.readNull();
        this.player = null;
      } else {
        if (this.player == null) {
          this.player = new Wager_odds_player();
        }
        this.player.customDecode(in);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.system = null;
      } else {
        if (this.system == null) {
          this.system = new Wager_odds_system();
        }
        this.system.customDecode(in);
      }

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          if (in.readIndex() != 1) {
            in.readNull();
            this.player = null;
          } else {
            if (this.player == null) {
              this.player = new Wager_odds_player();
            }
            this.player.customDecode(in);
          }
          break;

        case 1:
          if (in.readIndex() != 1) {
            in.readNull();
            this.system = null;
          } else {
            if (this.system == null) {
              this.system = new Wager_odds_system();
            }
            this.system.customDecode(in);
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










